apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
certificateKey: "c78d0bb0ca65f9e27488cfcb0f63d9dd450f95a6384510854b20ca2f51b19ad5" # kubeadm certs certificate-key
bootstrapTokens:
- groups:
  -  system:bootstrappers:kubeadm:default-node-token
  token: "37ohjj.1e7r92u1yapgpp0i" # kubeadm token generate
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: nucles
controlPlaneEndpoint: nucles.localdomain:6443
apiServer:
  certSANs:
  - nucles.localdomain
  - sergio.localdomain
  - nucle1.localdomain
  - nucle2.localdomain
  - nucle3.localdomain
  extraArgs:
    feature-gates: MixedProtocolLBService=true
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
allowedUnsafeSysctls:
  - net.ipv4.conf.all.src_valid_mark
