apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: nucles.localdomain:6443
    token: "37ohjj.1e7r92u1yapgpp0i" # from kubeadm-init.yaml or `kubeadm token create`
    unsafeSkipCAVerification: true
