hiddenMemberFields:
  - "TypeMeta"

hideTypePatterns:
  - "ParseError$"
  # - "List$"

stripPrefix:
  - k8s.io/api/
  - k8s.io/apimachinery/pkg/apis/
  - github.com/tengqm/kubeconfig/config/kubeadm/v1beta2.
  - github.com/tengqm/kubeconfig/config/kubeadm/v1beta3.
  - github.com/tengqm/kubeconfig/config/bootstraptoken/v1.

mappings:
  meta/v1.Duration: duration # string regex pls
  core/v1.Taint: "(import ./core.v1.nix).Taint"

apis:
  - name: core
    package: k8s.io/api
    path: core/v1

  - name: kubelet-config
    package: k8s.io/kubelet
    path: config/v1beta1
    includes:
      - k8s.io/component-base/logs/api/v1
      - k8s.io/component-base/tracing/api/v1

  - name: kubelet-config
    package: k8s.io/kubelet
    path: config/v1
    includes:
      - k8s.io/component-base/logs/api/v1
      - k8s.io/component-base/tracing/api/v1

  # - name: kubelet-credentialprovider
  #   package: k8s.io/kubelet
  #   path: pkg/apis/credentialprovider/v1alpha1

  # - name: kubelet-credentialprovider
  #   package: k8s.io/kubelet
  #   path: pkg/apis/credentialprovider/v1beta1

  # - name: kubelet-credentialprovider
  #   package: k8s.io/kubelet
  #   path: pkg/apis/credentialprovider/v1

  # - name: kube-scheduler-config
  #   package: k8s.io/kube-scheduler
  #   path: config/v1beta2
  #   includes:
  #     - k8s.io/component-base/config/v1alpha1

  # - name: kube-scheduler-config
  #   package: k8s.io/kube-scheduler
  #   path: config/v1beta3
  #   includes:
  #     - k8s.io/component-base/config/v1alpha1

  - name: kube-scheduler-config
    package: k8s.io/kube-scheduler
    path: config/v1
    includes:
      - k8s.io/component-base/config/v1alpha1

  # - name: kube-scheduler-extender
  #   package: k8s.io/kube-scheduler
  #   path: extender/v1

  - name: kube-controller-manager-config
    package: k8s.io/kube-controller-manager
    path: config/v1alpha1
    includes:
      - k8s.io/cloud-provider/controllers/service/config/v1alpha1
      - k8s.io/cloud-provider/config/v1alpha1
      - k8s.io/controller-manager/config/v1alpha1

  - name: kube-proxy-config
    package: k8s.io/kube-proxy
    path: config/v1alpha1
    includes:
      - k8s.io/component-base/config/v1alpha1

  # v1alpha1 is preserved because TracingConfiguration is referenced.
  - name: apiserver-config
    package: k8s.io/apiserver
    path: pkg/apis/apiserver/v1alpha1

  # v1beta1 is preserved because it has different types exposed.
  - name: apiserver-config
    package: k8s.io/apiserver
    path: pkg/apis/apiserver/v1beta1

  - name: apiserver-config
    package: k8s.io/apiserver
    path: pkg/apis/apiserver/v1

  # Note: This is named as apiserver-encryption because the so called config
  # pkg only contains encryption config. Need to differentiate it from the
  # apiserver-config above.
  # - name: apiserver-encryption
  #   package: k8s.io/apiserver
  #   path: pkg/apis/config/v1

  # Note: This is named apiserver-audit because it is part of the apiserver module
  # - name: apiserver-audit
  #   package: k8s.io/apiserver
  #   path: pkg/apis/audit/v1

  # - name: apiserver-resourcequota
  #   package: k8s.io/apiserver
  #   path: pkg/admission/plugin/resourcequota/apis/resourcequota/v1

  # - name: apiserver-webhookadmission
  #   package: k8s.io/apiserver
  #   path: pkg/admission/plugin/webhook/config/apis/webhookadmission/v1

  # - name: apiserver-eventratelimit
  #   package: github.com/tengqm/kubeconfig
  #   path: config/admission/eventratelimit/apis/v1alpha1
