# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "ahci" "mpt3sas" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ecc19012-49de-47fc-869d-d49f432ee6b8";
    fsType = "btrfs";
  };

  fileSystems."/esp" = {
    device = "/dev/disk/by-uuid/94AE-643B";
    fsType = "vfat";
  };
  
  fileSystems."/boot" = {
    device = "/esp/EFI/Nix";
    fsType = "none";
    options "bind";
  }

  swapDevices = [{
    device = "/dev/nvme0n1p3";
  }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
